apiVersion: v1
kind: Service
metadata:
    name: api-cluster-ip-service
spec:
    type: clusterIP
    ports:
        - port:  3000
          targetPort: 3000
    selector:
        component: api
